// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Same fallback chain as lib/db.ts so `prisma migrate` works on
    // Vercel-Postgres-style environments that only set POSTGRES_* vars
    url:
      process.env["DATABASE_URL"] ||
      process.env["POSTGRES_URL"] ||
      process.env["POSTGRES_PRISMA_URL"] ||
      process.env["POSTGRES_URL_NON_POOLING"],
  },
});
